### PR TITLE
Milestone7.0

### PR DESCRIPTION
**Pull request by tsahi**
This PR breaks the Data Access Application Block into several NuGet packages, setting the stage for future updates of each database support library, without requiring the user to add dependencies on packages he won't really use. This is an implementation of issue #39, and smaller bugs (#14, #23, #31, #32).
I suppose the build process will have to be modified to accommodate this change, but this is beyond my control.
Following this PR, we should upload the generated NuGet packages to nuget.org (again, beyond my control) and write release notes.

Note that this is versioned as 7.0 RC1. While I'm confident this is production ready, it's always good to get some user feedback first.

### CODE REVIEW

**Comment by Chavoshi** [comment]
@tsahi , I've merged your changes into master and drafted a release, can you please update the release note? 
BTW, the NuGet packages are ready to publish. I did my own testings but since you are more aware of the changes, I'll publish them with your green light. Thanks,

**Comment by tsahi** [comment]
@Chavoshi I added release notes to the release, copied from the page I published at https://enterpriselibrary.github.io/daab/a00950.html.

**Comment by Chavoshi** [comment]
@tsahi, Microsoft has reserved the EnterpriseLibrary prefix in NuGet.org so we cannot push any new packages with that prefix, BTW, it is fine for the existing ones, but since we are publishing 5 new packages, we have to come up with another prefix.
Maybe @mjrousos can help us in this matter.

**Comment by Chavoshi** [comment]
@tsahi , what do you think of changing the new packages prefixes?

**Comment by tsahi** [comment]
@Chavoshi if there is no other choice, we can do it. Have you tried contacting Microsoft other than  @mjrousos ?

**Pull request merged**
