### PR TITLE
Fix #32

### LINKED ISSUE #32: DatabaseProviderFactory.Create(String) fails for an ODBC provider under .NET Core
When trying to create a `GenericDatabase` in order to work with a `System.Data.Odbc` provider under .NET Core, `DatabaseProviderFactory.Create(String)` creates a `SqlDatabase` instead. This fails the test at https://github.com/EnterpriseLibrary/data-access-application-block/blob/27bedfcc43147c19e9620d983098d5fa8d54a025/source/Tests/Data.Tests/GenericDatabaseFixture.cs#L26-L35 under .NET Core. We should either:
1. Disable this test and remove support for ODBC under .NET Core
2. Add a dependency on [System.Data.Odbc](https://www.nuget.org/packages/System.Data.Odbc/) in .NET Core, which I believe will solve the issue (haven't tried yet).

What do you think?

As a side note, we should consider if `GenericDatabase` is the best fit for ODBC, since it doesn't support `DeriveParameters()`, while `OdbcCommandBuilder` does, depending on the underlying data source.

### PR DESCRIPTION
**Pull request by tsahi**
This essentially fixes #32 . I didn't realize a validation method will alter the object it is validating, to map any tested provider name to `SqlClientFactory`, which is why any bogus provider name returned an `SqlDatabase`.
https://github.com/EnterpriseLibrary/data-access-application-block/blob/5dd739905814ed41123c9885bd14963bd675a970/source/Src/Data/Configuration/DatabaseSyntheticConfigSettings.cs#L161

As of now, all tests pass, except one reported as #31

### CODE REVIEW

**Comment by Chavoshi** [comment]
Are tests are running in all frameworks?
I remember there was an issue with netcoreapp2.0.

@moein-shafiei

**Comment by tsahi** [comment]
There are net47 and netcoreapp3.0 tests (not sure how this is working, actually). How would you run tests in other frameworks?

Anyway, looks wrong to me to modify the tested object while testing it, and to register any provider name as SqlClientFactory.

**Comment by Chavoshi** [comment]
Actually the problem is with DbProviderFactories which was existed before .Net Core 2.2 and got added after that.
So in order to support frameworks before 2.2 we had to bring that functionality inside the EntLib itself. But the problem is the new DbProviderFactories behaviour is different than the old one as the logic has to be taken care differently.

BTW, I totally agree with you which it was not a good idea to handle this problem here.
And also let me express my interest of depreciating the older .Net Core frameworks.

**Comment by tsahi** [comment]
I tried to find usage statics for .net versions, but couldn't find any. However, [this document](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) outlines the end of support dates of .NET Core versions. v2.1 is supported until Aug. 2021, so I don't know if we can deprecate it.

**Comment by tsahi** [comment]
`DbProviderFactories`[ exists since .net core 2.1](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbproviderfactories?view=netcore-2.1#moniker-applies-to). The problem I see is that   `OleDbConnectionStringBuilder` exists only[ starting from .net core 3.0](https://docs.microsoft.com/en-us/dotnet/api/system.data.oledb.oledbconnectionstringbuilder?view=dotnet-plat-ext-3.1#moniker-applies-to) (as an extension).

**Comment by tsahi** [comment]
From what I see, the problem with .NET Core < 3.0 is only with the tests, specifically at https://github.com/EnterpriseLibrary/data-access-application-block/blob/47b9ebba811dac945091e61ac988a14388701d8a/source/Tests/Data.Tests/Configuration/Fluent/Given_ConfigureDataEntryPoint.cs#L22
other than that, the Data project doesn't use types not supported by netcore2.0.

**Pull request merged**
